[package]
name = "zhell-render"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
description = "Zhell GPU renderer (wgpu): glyph atlas, box drawing, images, background shaders"
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
wgpu.workspace = true
naga.workspace = true
pollster.workspace = true
sys-locale = "0.3"

cosmic-text.workspace = true
bytemuck.workspace = true
log.workspace = true
thiserror.workspace = true

[target.'cfg(all(unix, not(any(target_os = "macos", target_os = "android"))))'.dependencies]
fontconfig-parser = "0.5"
